name: behomie
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - res/language/

  uses-material-design: true
#  fonts:
#     - family: Opun
#       fonts:
#         - asset: res/fonts/Opun-Thin.ttf
#           weight: 100
#         - asset: res/fonts/Opun-ExtraLight.ttf
#           weight: 200
#         - asset: res/fonts/Opun-Light.ttf
#           weight: 300
#         - asset: res/fonts/Opun-Regular.ttf
#           weight: 400
